version: "3.8"
services:

  jwtApp:
    image: jwtapp
    build: .
    container_name: jwtapp
    ports:
      - "8080:8080"
    links:
      - jwtmongodb

  mongodb:
    image: mongo
    container_name: jwtmongodb
    ports:
      - "27017:27017"
    volumes:
      - jwtMongoDbVol:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongoexpress:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    restart: always
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SEVER=jwtmongodb

volumes:
  jwtMongoDbVol:
networks:
  default:
    name: mongodb_network
